### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gabriel-santanna** [gugarosa/opfython#1]
Usage of fit in supervised models gives error:

AttributeError: 'int' object has no attribute 'item'

**To Reproduce**
1)from opfython.models import SupervisedOPF
2)opf = SupervisedOPF(distance='log_squared_euclidean', pre_computed_distance=None)
3) opf.fit(X_train, y_train)

4) Error:

AttributeError                            Traceback (most recent call last)
<ipython-input-35-7007df241eb6> in <module>
----> 1 opf.fit(X_train, y_train)

/opt/conda/lib/python3.7/site-packages/opfython/models/supervised.py in fit(self, X_train, Y_train, I_train)
    135 
    136         # Creating a subgraph
--> 137         self.subgraph = Subgraph(X_train, Y_train, I=I_train)
    138 
    139         # Finding prototypes

/opt/conda/lib/python3.7/site-packages/opfython/core/subgraph.py in __init__(self, X, Y, I, from_file)
     58 
     59             # Now, we need to build this class up
---> 60             self._build(X, Y, I)
     61 
     62         # If data could not be loaded

/opt/conda/lib/python3.7/site-packages/opfython/core/subgraph.py in _build(self, X, Y, I)
    204             # If not, just creates the Node
    205             else:
--> 206                 node = Node(i, label.item(), feature)
    207 
    208             # Appends the node to the list

AttributeError: 'int' object has no attribute 'item'

Enviroment was:
 - Kaggle cloud virtualization of Anaconda
 - Python Version  3.7

**Comment by gugarosa** [comment]
According to the docs (https://opfython.readthedocs.io/en/latest/api/opfython.models.html#opfython.models.SupervisedOPF), y_train should be a numpy array. Probably it is being used as a list, therefore an indexed item will not have the .item() function that is found on the numpy array.

Best regards,
Gustavo.

**Comment by gabriel-santanna** [comment]
I did tried converting my X_train and y_train to numpy arrays
When i use as a parameter:
1)X_train.to_numpy() and y_train.to_numpy()

i still get the following error
![Screenshot from 2020-12-26 12-19-19](https://user-images.githubusercontent.com/76575769/103154263-fbba4880-4774-11eb-9282-64767a44e4d0.png)


I printed the distribution of values in my y_train just below the said error
Not sure how to proceed

With appreciation,
Gabriel Sant'anna

**Comment by gugarosa** [comment]
Labels should be greater or equal than 1. It is not possible to have a 0 in your y_train array.

Best regards,
Gustavo.
