### ISSUE TITLE
Question about computing input indicators importance

### ISSUE THREAD

**Issue by Ari-lily** [gugarosa/opfython#12]
Hello gugarosa!
I have some questions when using the OPF algorithm for slope stability classification project. Can the OPF algorithm be implemented to **calculate the importance of each input index**? Like the RandomForest algorithm, it is possible to calculate its "Gini importance" through "sklearn".

If so, please let me know how to calculate it.

Thank you very much and have a nice life!

**Comment by gugarosa** [comment]
Hello @Ari-lily! I hope everything is going well with you.

To the best of my knowledge, Gini Importance (Mean Decrease in Impurity - MDI) is usually applied in tree-based models and I have not seen any reference regarding its usage in graph-based classifiers.

Nevertheless, it seems that sklearn implements a type of Permutation Feature Importance which might be suitable to your case: https://scikit-learn.org/stable/modules/permutation_importance.html.

Please take a look at it and let me know if it works!

Best regards,
Gustavo.

**Comment by Ari-lily** [comment]
> Hello @Ari-lily! I hope everything is going well with you.
> 
> To the best of my knowledge, Gini Importance (Mean Decrease in Impurity - MDI) is usually applied in tree-based models and I have not seen any reference regarding its usage in graph-based classifiers.
> 
> Nevertheless, it seems that sklearn implements a type of Permutation Feature Importance which might be suitable to your case: https://scikit-learn.org/stable/modules/permutation_importance.html.
> 
> Please take a look at it and let me know if it works!
> 
> Best regards, Gustavo.

Hello Gustavo!

Thank you very much for your reply!

I tried to use the "permutation_importance" in the "sklearn" package you mentioned to calculate the importance of the input indicators of the OPF classification algorithm.

But I got an error.
![830c7a0187d7236887851930567a30d](https://user-images.githubusercontent.com/101267594/172001371-d0c110b6-cc9e-496e-9d72-c77e2b31d4e8.png)

Is there a solution to this problem?
Or how to use the OPF algorithm to calculate the importance of input indicators.

Thank you very much and have a nice life!

**Comment by gugarosa** [comment]
You will probably have to inherit the OPF class into a new class and adapt the missing arguments according to the ones that `PermutationImportance` requires.

I suggest that you take a look at its source code or even one of the sklearn's classifiers to see which are the missing arguments that the OPF class might need.

Best regards,
Gustavo.

**Comment by Ari-lily** [comment]
> You will probably have to inherit the OPF class into a new class and adapt the missing arguments according to the ones that `PermutationImportance` requires.
> 
> I suggest that you take a look at its source code or even one of the sklearn's classifiers to see which are the missing arguments that the OPF class might need.
> 
> Best regards, Gustavo.

Thank you very much for your reply, it helps me a lot!
Have a great day!
