### ISSUE TITLE
[REG]Questions about OPF classifier performance evaluation

### ISSUE THREAD

**Issue by Ari-lily** [gugarosa/opfython#7]
## Template when making a new issue

Please, make sure that the following boxes are checked before submitting a new issue. There is a small chance that you can solve it by your own or even that it was already addressed by someone.

Thank you!

### Pre-checkings

- [√ ] Check that you are up-to-date with the master branch of OPFython. You can update with:
pip install git+git://github.com/gugarosa/opfython.git --upgrade --no-deps

- [ √] Check that you have read all of our [README](https://github.com/gugarosa/opfython/blob/master/README.md).

### Description

[Description of the issue]
      I have a question for the authors about the OPF algorithm. After using the OPF algorithm for classification, I need to evaluate the algorithm, then I choose to plot the ROC curve to evaluate the performance of the classifier, I use the "fpr, tpr, thresholds = metrics.roc_curve(y_true, y_score)" in the sklearn library to calculate fpr and tpr. " to calculate fpr and tpr, now I know "y_true", how to calculate this "y_score"?
      I checked the user guide of the sklearn library and it gives the following explanation: In the binary case, it corresponds to an array of shape (n_samples,). Both probability estimates and non-thresholded decision values can be provided. with the greater label.
     So how to calculate this "y_score" in the OPF algorithm?
     I plotted the ROC with the predicted label as the "y_score", and the resulting graph has only one inflection point.
    
    ![Uploading c88503873929dd64c06789b019bd50a.png…]()
    
    Thank you！！！

**Comment by gugarosa** [comment]
Hello @Ari-lily! I hope everything is going well with you!

Regarding the predicted probabilities, the standard Optimum-Path Forest classifier is not capable of doing so. It only outputs the hard-coded labels of the classes. Nevertheless, there is a recent paper in the literature, proposed by Fernandes et al., which introduces a probabilistic-based version of the OPF: https://ieeexplore.ieee.org/document/8329170

In order to produce scikit probabilities-like (which I think is the `y_score` you want to use), you would need to implement such a version.

Best regards,
Gustavo.

**Comment by Ari-lily** [comment]
> Hello @Ari-lily! I hope everything is going well with you!
> 
> Regarding the predicted probabilities, the standard Optimum-Path Forest classifier is not capable of doing so. It only outputs the hard-coded labels of the classes. Nevertheless, there is a recent paper in the literature, proposed by Fernandes et al., which introduces a probabilistic-based version of the OPF: https://ieeexplore.ieee.org/document/8329170
> 
> In order to produce scikit probabilities-like (which I think is the `y_score` you want to use), you would need to implement such a version.
> 
> Best regards, Gustavo.

I really appreciate your reply, it helps me a lot, have a nice life!

**Comment by Ari-lily** [comment]
Hello gugarosa!
I have some questions when using the OPF algorithm for slope stability classification project. Can the OPF algorithm be implemented to **calculate the importance of each input index**? Like the RandomForest algorithm, it is possible to calculate its "Gini importance" through "sklearn".

If so, please let me know how to calculate it.

Thank you very much and have a nice life!
